# Generated by Django 4.2.19 on 2025-02-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HRMSAPP", "0002_alter_hr_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hr",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
