# Generated by Django 5.1.7 on 2025-03-18 07:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255, unique=True)),
                ('ModifyDateTime', models.DateTimeField(auto_now=True)),
                ('DeletedDateTime', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_name', models.CharField(max_length=255, unique=True)),
                ('qualification_desc', models.TextField(blank=True, null=True)),
                ('ModifyDateTime', models.DateTimeField(auto_now=True)),
                ('DeletedDateTime', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=13)),
                ('resume', models.FileField(upload_to='resume/')),
                ('is_experienced', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('date_of_birth', models.DateField()),
                ('father_name', models.CharField(max_length=255)),
                ('address', models.TextField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('gap', models.IntegerField(blank=True, default=0, null=True)),
                ('last_company', models.CharField(blank=True, max_length=255, null=True)),
                ('exp_years', models.IntegerField(blank=True, default=0, null=True)),
                ('ModifyDateTime', models.DateTimeField(blank=True, null=True)),
                ('DeletedDateTime', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('domain_of_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates_interest', to='HRMSAPP.domaininterest')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates_qualification', to='HRMSAPP.qualification')),
            ],
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.CharField(max_length=200, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TechArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_specification', models.CharField(max_length=255, unique=True)),
                ('ModifyDateTime', models.DateTimeField(auto_now=True)),
                ('DeletedDateTime', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('DeletedByUserid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_tech', to=settings.AUTH_USER_MODEL)),
                ('ModifiedByUserid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_tech', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='qualification',
            name='DeletedByUserid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_qualification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qualification',
            name='ModifiedByUserid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_qualification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModifyDateTime', models.DateTimeField(blank=True, null=True)),
                ('DeletedDateTime', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('interviewers', models.TextField(blank=True, null=True)),
                ('stage', models.CharField(choices=[('Screening', 'Screening'), ('Technical', 'Technical'), ('HR', 'HR'), ('Final', 'Final')], max_length=50)),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=50)),
                ('status', models.CharField(blank=True, choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=50, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('candidate_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_candidate', to='HRMSAPP.candidate')),
                ('DeletedByUserid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_interviews', to=settings.AUTH_USER_MODEL)),
                ('ModifiedByUserid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_interviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='domaininterest',
            name='DeletedByUserid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_domains', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domaininterest',
            name='ModifiedByUserid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_domains', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CandidateTechArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModifyDateTime', models.DateTimeField(auto_now=True)),
                ('DeletedDateTime', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMSAPP.candidate')),
                ('tech_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMSAPP.techarea')),
                ('DeletedByUserid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_candidate_tech', to=settings.AUTH_USER_MODEL)),
                ('ModifiedByUserid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_candidate_tech', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='DeletedByUserid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delete_record', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidate',
            name='ModifiedByUserid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifier', to=settings.AUTH_USER_MODEL),
        ),
    ]
