# Generated by Django 4.2.19 on 2025-02-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HRMSAPP", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hr",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
