# Generated by Django 4.2.13 on 2025-03-10 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='hr',
            managers=[
            ],
        ),
    ]
