# Generated by Django 5.1.6 on 2025-03-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Female', max_length=100, null=True),
        ),
    ]
