# Generated by Django 5.1.7 on 2025-03-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSAPP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='stage',
            new_name='round',
        ),
        migrations.AlterField(
            model_name='interview',
            name='mode',
            field=models.CharField(choices=[('Virtual', 'Virtual'), ('Onsite', 'Onsite')], max_length=50),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], max_length=50, null=True),
        ),
    ]
