# Generated by Django 4.2.13 on 2025-03-11 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSAPP', '0002_alter_hr_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hr',
            old_name='IsDeleted',
            new_name='is_deleted',
        ),
    ]
