# Generated by Django 5.1.7 on 2025-03-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSAPP', '0002_rename_stage_interview_round_alter_interview_mode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='round',
            new_name='stage',
        ),
        migrations.AlterField(
            model_name='interview',
            name='mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=50),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(blank=True, choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=50, null=True),
        ),
    ]
