# Generated by Django 4.2.19 on 2025-02-28 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("HRMSAPP", "0003_alter_hr_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="area",
        ),
    ]
