# Generated by Django 5.1.7 on 2025-03-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSAPP', '0003_rename_round_interview_stage_alter_interview_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='mode',
            field=models.CharField(choices=[('Virtual', 'Virtual'), ('OnSite', 'OnSite')], max_length=50),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], max_length=50, null=True),
        ),
    ]
