# Generated by Django 4.2.13 on 2025-03-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSAPP', '0003_rename_isdeleted_hr_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True),
        ),
    ]
