# Generated by Django 5.1.7 on 2025-03-18 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSAPP', '0004_alter_interview_mode_alter_interview_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='stage',
            new_name='round',
        ),
    ]
