# Generated by Django 4.2.13 on 2025-03-17 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSAPP', '0004_alter_hr_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModifyDateTime', models.DateTimeField(blank=True, null=True)),
                ('DeletedDateTime', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('interviewers', models.TextField(blank=True, null=True)),
                ('stage', models.CharField(choices=[('Screening', 'Screening'), ('Technical', 'Technical'), ('HR', 'HR'), ('Final', 'Final')], max_length=50)),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=50)),
                ('status', models.CharField(blank=True, choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=50, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('DeletedByUserid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_interviews', to=settings.AUTH_USER_MODEL)),
                ('ModifiedByUserid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_interviews', to=settings.AUTH_USER_MODEL)),
                ('candidate_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_candidate', to='HRMSAPP.candidate')),
            ],
        ),
    ]
