# Generated by Django 4.2.13 on 2025-03-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSAPP', '0004_alter_hr_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='IsDeleted',
            new_name='is_deleted',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='domain_of_interest',
            field=models.ManyToManyField(blank=True, related_name='candidates', to='HRMSAPP.domaininterest'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='qualification',
            field=models.ManyToManyField(blank=True, related_name='candidates', to='HRMSAPP.qualification'),
        ),
    ]
