# Generated by Django 4.2.13 on 2025-03-17 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSAPP', '0005_interview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='review',
            new_name='remark',
        ),
    ]
