# Generated by Django 4.2.13 on 2025-03-05 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSAPP', '0005_rename_isdeleted_candidate_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hr',
            name='username',
        ),
    ]
