# Generated by Django 4.2.13 on 2025-03-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSAPP', '0006_remove_hr_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
