# Generated by Django 4.2.13 on 2025-03-05 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSAPP', '0007_hr_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hr',
            name='username',
        ),
    ]
