# Generated by Django 4.2.13 on 2025-03-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSAPP', '0008_remove_hr_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatetecharea',
            old_name='deleted_by',
            new_name='DeletedByUserid',
        ),
        migrations.RenameField(
            model_name='candidatetecharea',
            old_name='deleted_date',
            new_name='DeletedDateTime',
        ),
        migrations.RenameField(
            model_name='candidatetecharea',
            old_name='modified_by',
            new_name='ModifiedByUserid',
        ),
        migrations.RenameField(
            model_name='candidatetecharea',
            old_name='modified_date',
            new_name='ModifyDateTime',
        ),
        migrations.RenameField(
            model_name='domaininterest',
            old_name='deleted_by',
            new_name='DeletedByUserid',
        ),
        migrations.RenameField(
            model_name='domaininterest',
            old_name='deleted_date',
            new_name='DeletedDateTime',
        ),
        migrations.RenameField(
            model_name='domaininterest',
            old_name='modified_by',
            new_name='ModifiedByUserid',
        ),
        migrations.RenameField(
            model_name='domaininterest',
            old_name='modified_date',
            new_name='ModifyDateTime',
        ),
        migrations.RenameField(
            model_name='qualification',
            old_name='deleted_by',
            new_name='DeletedByUserid',
        ),
        migrations.RenameField(
            model_name='qualification',
            old_name='deleted_date',
            new_name='DeletedDateTime',
        ),
        migrations.RenameField(
            model_name='qualification',
            old_name='modified_by',
            new_name='ModifiedByUserid',
        ),
        migrations.RenameField(
            model_name='qualification',
            old_name='modified_date',
            new_name='ModifyDateTime',
        ),
        migrations.RenameField(
            model_name='techarea',
            old_name='deleted_by',
            new_name='DeletedByUserid',
        ),
        migrations.RenameField(
            model_name='techarea',
            old_name='deleted_date',
            new_name='DeletedDateTime',
        ),
        migrations.RenameField(
            model_name='techarea',
            old_name='modified_by',
            new_name='ModifiedByUserid',
        ),
        migrations.RenameField(
            model_name='techarea',
            old_name='modified_date',
            new_name='ModifyDateTime',
        ),
    ]
