# Generated by Django 4.2.13 on 2025-03-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSAPP', '0009_rename_deleted_by_candidatetecharea_deletedbyuserid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='resume',
        ),
        migrations.AddField(
            model_name='candidate',
            name='cv',
            field=models.FileField(default='NA', upload_to='cv/'),
        ),
    ]
